blank_issues_enabled: true
contact_links:
  - name: ğŸ‘¥ Discussions
    url: https://github.com/guirre/designPatterns/discussions/new
    about: Please use discussions for issues that are not a bug, enhancement or feature request
